name: Build and Push to Docker Hub

on:
  push:
    branches:
      - main  # Se ejecuta cuando hay cambios en la rama principal

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Iniciar sesión en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.HUB_TOKEN }}

      - name: Construir la imagen Docker
        run: docker build -t tu_usuario/mi-app:latest .

      - name: Subir la imagen a Docker Hub
        run: docker push ${{secrets.DOCKER_HUB_USERNAME}}/mi-app:latest
