name: Docker CI

on:
  push:
    branches:
      - main  # Activa el workflow cuando se hace push a la rama main
  pull_request:
    branches:
      - main  # Activa el workflow cuando se crea un pull request a la rama main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código
      - name: Checkout repository
        uses: actions/checkout@v3

      # Paso 2: Inicia sesión en Docker Hub (opcional, solo si vas a subir la imagen)
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Paso 3: Construye la imagen Docker
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/my_docker_ava:latest .

      # Paso 4: Prueba la imagen (opcional)
      - name: Run tests
        run: docker run ${{ secrets.DOCKER_HUB_USERNAME }}/my_docker_ava:latest npm test

      # Paso 5: Sube la imagen a Docker Hub (opcional)
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/my_docker_ava:latest
